spring:
  application:
    name: organizationservice
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8100